inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Exclude:
    - 'spec/dummy/db/**/*.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'logux_rails.gemspec'
    - 'lib/logux/test/helpers.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/logux/tasks/*.rb'
    - 'spec/requests/*.rb'

FactoryBot/StaticAttributeDefinedDynamically:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/DateTime:
  Enabled: false
